#! /bin/sh
#  @version $Revision$ ($Author$) $Date$
#
# This is environment specific file stored here for reference
# located in build environment in ${BUILD_HOME}/bin

export ANT_OPTS="${ANT_OPT} -Djava.awt.headless=true"
export ANT_OPTS="${ANT_OPT} -Xms80m"
export ANT_OPTS="${ANT_OPT} -Xmx150m"

runAnt() {
    echo START ANT BUILD [${JAVA_HOME}]
    ${ANT_HOME}/bin/ant $@
    if [ $? -ne 0 ]
    then
        echo Error in ${JAVA_HOME} build
        exit 1
    else
        echo ANT BUILD [${JAVA_HOME}] SUCCESSFUL
    fi
}

export JAVA_HOME=/usr/java/jdk1.4.2
runAnt $@

export JAVA_HOME=/usr/java/jdk1.5.0
runAnt $@

export JAVA_HOME=/usr/java/jdk1.6.0
runAnt $@

